# Project build settings (Gradle).
# Note: the confidential settings are in file "~/.gradle/gradle.properties".

APP_NAME = Aplino
APP_SHORT_NAME = aplino
APP_VERSION = 1.4
APP_DESCRIPTION = "Application development framework in Kotlin"
APP_MANUFACTURER = dimi2
APP_GROUP = dev.strategia

# Minimum build tools versions.
minJavaVersion = 25
minGradleVersion = 9.5.1
minKotlinVersion = 2.3.21

dokkaVersion = 2.2.0
detektVersion = 2.0.0-alpha.3
nmcpVersion = 1.4.4

# Additional settings.
org.gradle.warning.mode = all
org.gradle.configuration-cache = true
