# Set status level
status = warn

# Property definition
property.logFileName = aplino

# Appenders
appender.rolling.type = RollingFile
appender.rolling.name = logFile
appender.rolling.fileName = ${sys:TEMP_DIR}/${logFileName}.log
appender.rolling.filePattern = ${logFileName}-%d{MM-dd-yyyy}-%i.log.gz
appender.rolling.append = true
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.alwaysWriteExceptions = false
appender.rolling.layout.pattern = %d{yyyy-MM-dd'T'HH:mm:ss.SSS};%level;%c;%msg%n%ex%n
appender.rolling.policies.type = Policies
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 10 MB

# Loggers
logger.aplino.name = dev.strategia.aplino
logger.aplino.level = warn
logger.aplino.additivity = false
logger.aplino.appenderRef.rolling.ref = logFile

# Root logger
rootLogger.level = warn
rootLogger.appenderRef.rolling.ref = logFile